name: Renovate
on:
  schedule:
    - cron: '0/60 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.71.3
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
