name: Renovate
on:
  schedule:
    - cron: '0 0 15 * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.74.2
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
